# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY cmd/ ./cmd
COPY server/ ./server
COPY log/ ./log
COPY knox.go knox_test.go ./

RUN go build -tags netgo ./cmd/dev_server
RUN chmod +x ./dev_server

##
## Deploy
##
FROM alpine:latest

WORKDIR /

COPY --from=build /app/dev_server /knox-server
EXPOSE 9000

ENTRYPOINT ["/knox-server"]
