# syntax=docker/dockerfile:1

##
## Build
##
FROM --platform=linux/amd64 golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY cmd/ ./cmd
COPY client/ ./client
COPY log/ ./log
COPY client.go client_test.go knox.go knox_test.go ./

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build ./cmd/dev_client
RUN chmod +x ./dev_client

##
## Deploy
##
FROM --platform=linux/amd64 alpine:latest

WORKDIR /

COPY --from=build /app/dev_client /knox-client

ENTRYPOINT ["sh", "-c", "--" ]
CMD [ "while true; do sleep 30; done;" ]
