apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sm-proxy
  name: cm-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps"]
    resourceNames: ["spire-bundle"]
    verbs: ["get"]