apiVersion: v1
kind: Service
metadata:
  name: knox
spec:
  ports:
  - port: 9000
  selector:
    app: knox
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knox
spec:
  selector:
    matchLabels:
      app: knox
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: knox
    spec:
      serviceAccountName: knox
      imagePullSecrets:
      - name: sbercloud-harbor-dev
      initContainers:
      - name: init-spire-client
        image: gcr.io/spiffe-io/spire-agent:1.1.1
        command: [ "/bin/sh", "-c", "--"]
        args: ["/opt/spire/bin/spire-agent api fetch -socketPath /run/spire/sockets/agent.sock -write /certs"]
        volumeMounts:
          - name: spire-agent-socket
            mountPath: /run/spire/sockets
            readOnly: true
          - name: certs
            mountPath: /certs
      containers:
      - name: spire-client
        image: gcr.io/spiffe-io/spire-agent:1.1.1
        command: [ "/bin/sh", "-c", "--"]
        args: ["while true; do /opt/spire/bin/spire-agent api fetch -socketPath /run/spire/sockets/agent.sock -write /certs; sleep 10; done;"]
        volumeMounts:
          - name: spire-agent-socket
            mountPath: /run/spire/sockets
            readOnly: true
          - name: certs
            mountPath: /certs
      - image: registry.sbc.platform5.club/dev/knox:test-etcd
        name: knox
        imagePullPolicy: Always
        env:
        - name: CM_NAME
          value: spire-bundle
        - name: CRT_NAME
          value: bundle.crt
        - name: SPIFFE_CA_PATH
          value: /certs/bundle.crt
        - name: KNOX_DNS
          value: knox.{{ NAMESPACE }}:9000
        - name: DB_TYPE
          value: etcd
        - name: ETCD_ENDPOINTS
          value: etcd-0.etcd:2379;etcd-1.etcd:2379;etcd-2.etcd:2379
        - name: RSA_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: keycloak-public-key
              key: public-key.pem
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: AUTHZ_REGION
          value: AZ1
        - name: AUTHZ_ACCOUNT_ID
          value: "123"
        - name: AUTHZ_PROJECT_ID
          value: "456"
        - name: AUTHZ_RESOURCE_ID
          value: "789"
        - name: AUTHZ_OPA_URL
          value: http://opa:8181
        - name: AUTHZ_OPATIMEOUT
          value: "300"
        - name: AUTHZ_OPA_INSECURE
          value: "true"
        ports:
        - containerPort: 9000
          name: knox
        volumeMounts:
        - mountPath: /certs/bundle.crt
          name: spire-bundle
          subPath: bundle.crt
      volumes:
      - name: spire-bundle
        configMap:
          name: spire-bundle
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
      - name: certs
        emptyDir: {}
