apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-reader-rolebinding
  namespace: sm-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cm-reader
subjects:
  - namespace: sm-proxy
    kind: ServiceAccount
    name: default