# syntax=docker/dockerfile:1

##
## Build
##
FROM --platform=linux/amd64 golang:1.18-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY cmd/ ./cmd
COPY server/ ./server
COPY log/ ./log
COPY knox.go knox_test.go ./

RUN go build -tags netgo ./cmd/dev_server

##
## Deploy
##
FROM --platform=linux/amd64 alpine:latest

RUN apk add libc6-compat

WORKDIR /

ENV VERSION=v1.0.4
COPY --from=build /app/dev_server /knox-server
RUN chmod +x ./knox-server
EXPOSE 9000

ENTRYPOINT ["/knox-server"]
